\contentsline {lstlisting}{\numberline {3.1}{\ignorespaces JSON Information Model snippet}}{20}{lstlisting.3.1}%
\contentsline {lstlisting}{\numberline {3.2}{\ignorespaces A SHACL Shape generated by the pipeline}}{23}{lstlisting.3.2}%
\contentsline {lstlisting}{\numberline {3.3}{\ignorespaces YAML description of a scenario}}{26}{lstlisting.3.3}%
\contentsline {lstlisting}{\numberline {3.4}{\ignorespaces Excerpt of the reflexion prompt}}{29}{lstlisting.3.4}%
